### ISSUE TITLE
HYLODE alpha (Modelling MWE)

### ISSUE THREAD

**Issue by docsteveharris** [HYLODE/HyUi#124]
Defining the minimal working example of the full modelling system
That means we can

- [x] estimate LoS individually
- [ ] aggregate LoS per unit #70 
- [ ] estimate elective demand (tap)
- [ ] estimate emergency demand (tap)
- [ ] display the different aggregates together (abacus style) for the end user

Using this ticket to define for now the modelling delivery tasks
